"""Add created_at and updated_at to all tables

Revision ID: 204b9e909339
Revises: 7610edd42851
Create Date: 2025-09-13 01:14:45.414285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '204b9e909339'
down_revision: Union[str, Sequence[str], None] = '7610edd42851'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('authors', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('books', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('books', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('categories', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('categories', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('favorites', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('favorites', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('favorites', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('favorites', 'book_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint('uniq_favorite_per_user', 'favorites', ['user_id', 'book_id'])
    op.drop_constraint(op.f('favorites_book_id_fkey'), 'favorites', type_='foreignkey')
    op.drop_constraint(op.f('favorites_user_id_fkey'), 'favorites', type_='foreignkey')
    op.create_foreign_key(None, 'favorites', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'favorites', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('reading_list_books_reading_list_id_fkey'), 'reading_list_books', type_='foreignkey')
    op.drop_constraint(op.f('reading_list_books_book_id_fkey'), 'reading_list_books', type_='foreignkey')
    op.create_foreign_key(None, 'reading_list_books', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'reading_list_books', 'reading_lists', ['reading_list_id'], ['id'], ondelete='CASCADE')
    op.add_column('reading_lists', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('reading_lists', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('reading_lists', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('reading_lists', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('reading_lists_user_id_fkey'), 'reading_lists', type_='foreignkey')
    op.create_foreign_key(None, 'reading_lists', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('reviews', 'book_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reviews', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint('unique_review_per_user_book', 'reviews', ['rating', 'book_id'])
    op.drop_constraint(op.f('reviews_user_id_fkey'), 'reviews', type_='foreignkey')
    op.drop_constraint(op.f('reviews_book_id_fkey'), 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'reviews', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key(op.f('reviews_book_id_fkey'), 'reviews', 'books', ['book_id'], ['id'])
    op.create_foreign_key(op.f('reviews_user_id_fkey'), 'reviews', 'users', ['user_id'], ['id'])
    op.drop_constraint('unique_review_per_user_book', 'reviews', type_='unique')
    op.alter_column('reviews', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reviews', 'book_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'reading_lists', type_='foreignkey')
    op.create_foreign_key(op.f('reading_lists_user_id_fkey'), 'reading_lists', 'users', ['user_id'], ['id'])
    op.alter_column('reading_lists', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reading_lists', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('reading_lists', 'updated_at')
    op.drop_column('reading_lists', 'created_at')
    op.drop_constraint(None, 'reading_list_books', type_='foreignkey')
    op.drop_constraint(None, 'reading_list_books', type_='foreignkey')
    op.create_foreign_key(op.f('reading_list_books_book_id_fkey'), 'reading_list_books', 'books', ['book_id'], ['id'])
    op.create_foreign_key(op.f('reading_list_books_reading_list_id_fkey'), 'reading_list_books', 'reading_lists', ['reading_list_id'], ['id'])
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.create_foreign_key(op.f('favorites_user_id_fkey'), 'favorites', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('favorites_book_id_fkey'), 'favorites', 'books', ['book_id'], ['id'])
    op.drop_constraint('uniq_favorite_per_user', 'favorites', type_='unique')
    op.alter_column('favorites', 'book_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('favorites', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('favorites', 'updated_at')
    op.drop_column('favorites', 'created_at')
    op.drop_column('categories', 'updated_at')
    op.drop_column('categories', 'created_at')
    op.drop_column('books', 'updated_at')
    op.drop_column('books', 'created_at')
    op.drop_column('authors', 'updated_at')
    op.drop_column('authors', 'created_at')
    # ### end Alembic commands ###
