"""Add reading lists and related tables

Revision ID: ad42aaafa110
Revises: b55bfb1bdfb5
Create Date: 2025-09-11 23:20:31.631559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad42aaafa110'
down_revision: Union[str, Sequence[str], None] = 'b55bfb1bdfb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reading_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reading_lists_id'), 'reading_lists', ['id'], unique=False)
    op.create_index(op.f('ix_reading_lists_title'), 'reading_lists', ['title'], unique=False)
    op.create_table('reading_list_books',
    sa.Column('reading_list_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['reading_list_id'], ['reading_lists.id'], ),
    sa.PrimaryKeyConstraint('reading_list_id', 'book_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reading_list_books')
    op.drop_index(op.f('ix_reading_lists_title'), table_name='reading_lists')
    op.drop_index(op.f('ix_reading_lists_id'), table_name='reading_lists')
    op.drop_table('reading_lists')
    # ### end Alembic commands ###
