"""Add reading lists and related tables

Revision ID: b55bfb1bdfb5
Revises: dd0ee2930e8e
Create Date: 2025-09-11 23:18:50.806373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b55bfb1bdfb5'
down_revision: Union[str, Sequence[str], None] = 'dd0ee2930e8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
