"""Add refresh_token to user model

Revision ID: fa152945a604
Revises: 97e9cf5917db
Create Date: 2025-09-09 12:56:31.827723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa152945a604'
down_revision: Union[str, Sequence[str], None] = '97e9cf5917db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('books_author_id_fkey'), 'books', type_='foreignkey')
    op.drop_constraint(op.f('books_category_id_fkey'), 'books', type_='foreignkey')
    op.create_foreign_key(None, 'books', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'books', 'authors', ['author_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('refresh_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'refresh_token')
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.create_foreign_key(op.f('books_category_id_fkey'), 'books', 'categories', ['category_id'], ['id'])
    op.create_foreign_key(op.f('books_author_id_fkey'), 'books', 'authors', ['author_id'], ['id'])
    # ### end Alembic commands ###
